### ISSUE TITLE
[BUG] LUA errors at the end of boss fights (CompactUnitFrame_Update.lua:8: calling 'ClearAllPoints' on bad self)

### ISSUE THREAD

**Issue by matcoga** [creed-us/Overshields_Reforged#4]
Hello, since I downloaded this addon, I sometimes get this error at the end of raid boss fights (current and old raid) :

```
70x ...Ons/Overshields_Reforged/CompactUnitFrame_Update.lua:8: calling 'ClearAllPoints' on bad self (Usage: self:ClearAllPoints())
[Overshields_Reforged/CompactUnitFrame_Update.lua]:8: in function <...Ons/Overshields_Reforged/CompactUnitFrame_Update.lua:5>
[C]: in function 'CompactUnitFrameUtil_UpdateFillBar'
[Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua]:1159: in function <...Ons/Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua:1024>
[C]: in function 'CompactUnitFrame_UpdateHealPrediction'
[Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua]:429: in function 'CompactUnitFrame_UpdateAll'
[Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua]:255: in function 'CompactUnitFrame_SetUnit'
[Blizzard_NamePlates/Blizzard_NamePlates.lua]:544: in function 'OnAdded'
[Blizzard_NamePlates/Blizzard_NamePlates.lua]:143: in function 'OnNamePlateAdded'
[Blizzard_NamePlates/Blizzard_NamePlates.lua]:79: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:70>

Locals:
frame = Button {
 debuffs = <table> {
 }
 WidgetContainer = Frame {
 }
 classificationIndicator = Texture {
 }
 HealthBarsContainer = Frame {
 }
 RaidTargetFrame = Frame {
 }
 maxDispelDebuffs = 0
 healPredictionDirty = true
 inVehicle = false
 displayedUnit = "nameplate2"
 optionTable = <table> {
 }
 overAbsorbGlow = Texture {
 }
 SoftTargetFrame = Frame {
 }
 totalAbsorb = Texture {
 }
 name = FontString {
 }
 aggroHighlight = Texture {
 }
 needsUpdate = true
 myHealAbsorbRightShadow = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 PlayerLevelDiffFrame = Frame {
 }
 ignoreCUFNameRequirement = true
 selectionHighlight = Texture {
 }
 myHealAbsorbLeftShadow = Texture {
 }
 maxDebuffs = 0
 unit = "nameplate2"
 unitExists = true
 disableMouse = true
 buffs = <table> {
 }
 newUnit = true
 castBar = StatusBar {
 }
 dispels = <table> {
 }
 hideHealthBarMask = 0
 BuffFrame = Frame {
 }
 LoseAggroAnim = AnimationGroup {
 }
 ClassificationFrame = Frame {
 }
 myHealAbsorb = Texture {
 }
 maxBuffs = 0
 totalAbsorbOverlay = Texture {
 }
 otherHealPrediction = Texture {
 }
 myHealPrediction = Texture {
 }
 isLootObject = false
 healthBar = StatusBar {
 }
}
previousTexture = Texture {
}
bar = Texture {
 overlay = Texture {
 }
}
amount = 0
barOffsetXPercent = nil

```

This error only happened at the end of encounters, but it's not systematic, I did not find something that may cause it specifically.
Also, this error can happen between 1 and 500 times (per fight, when it happens). For instance, in the error copied above (which was after killing mythic Fyrakk), it occurred 70 times.
Besides the error being there, it doesn't seem to cause any functionality problem.

Build infos :
![Image](https://github.com/user-attachments/assets/98c39e61-4935-4a95-8c98-ea33e9c65436)

I hope I provided enough information for you to investigate and hopefully find the cause of this error.

**Comment by creed-us** [comment]
I added some logic to account for what might've been happening there. Let me know if the bug persists after updating to v2.3.2! And thank you for the information.

**Comment by matcoga** [comment]
I updated to v2.3.2, and now I got this error during heroic Vexie and Rik (again, not systematic) :

```
390x ...Ons/Overshields_Reforged/CompactUnitFrame_Update.lua:10: calling 'GetObjectType' on bad self (Usage: local objectType = self:GetObjectType())
[Overshields_Reforged/CompactUnitFrame_Update.lua]:10: in function <...Ons/Overshields_Reforged/CompactUnitFrame_Update.lua:5>
[C]: in function 'CompactUnitFrameUtil_UpdateFillBar'
[Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua]:1159: in function <...Ons/Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua:1024>
[C]: in function 'CompactUnitFrame_UpdateHealPrediction'
[Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua]:429: in function <...Ons/Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua:403>
[C]: in function 'CompactUnitFrame_UpdateAll'
[Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua]:255: in function 'CompactUnitFrame_SetUnit'
[Blizzard_NamePlates/Blizzard_NamePlates.lua]:544: in function 'OnAdded'
[Blizzard_NamePlates/Blizzard_NamePlates.lua]:143: in function 'OnNamePlateAdded'
[Blizzard_NamePlates/Blizzard_NamePlates.lua]:79: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:70>

Locals:
frame = Button {
 WidgetContainer = Frame {
 }
 classificationIndicator = Texture {
 }
 HealthBarsContainer = Frame {
 }
 RaidTargetFrame = Frame {
 }
 maxDispelDebuffs = 0
 inVehicle = false
 optionTable = <table> {
 }
 overAbsorbGlow = Texture {
 }
 SoftTargetFrame = Frame {
 }
 totalAbsorb = Texture {
 }
 name = FontString {
 }
 aggroHighlight = Texture {
 }
 needsUpdate = true
 myHealAbsorbRightShadow = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 PlayerLevelDiffFrame = Frame {
 }
 ignoreCUFNameRequirement = true
 selectionHighlight = Texture {
 }
 myHealAbsorbLeftShadow = Texture {
 }
 maxDebuffs = 0
 unit = "nameplate3"
 unitExists = true
 disableMouse = true
 newUnit = true
 healPredictionDirty = true
 castBar = StatusBar {
 }
 displayedUnit = "nameplate3"
 hideHealthBarMask = 0
 BuffFrame = Frame {
 }
 LoseAggroAnim = AnimationGroup {
 }
 ClassificationFrame = Frame {
 }
 myHealAbsorb = Texture {
 }
 maxBuffs = 0
 totalAbsorbOverlay = Texture {
 }
 otherHealPrediction = Texture {
 }
 myHealPrediction = Texture {
 }
 isLootObject = false
 healthBar = StatusBar {
 }
}
previousTexture = Texture {
}
bar = Texture {
 overlay = Texture {
 }
}
amount = 0
barOffsetXPercent = nil
```

**Comment by creed-us** [comment]
That's my bad... I did not account for something that should've been obvious. Try using v2.3.3.

I'm also curious - as I've never encountered this error personally: Do you have any other addons that might be modifying the compact unit frames? I'd just like to integrate support where possible if it is an addon causing this.

**Comment by matcoga** [comment]
I'll be able to try this version in a few days. As for my addons that may interact with the compact unit frames, I'm thinking of :
BigDebuffs to change the appearance of certain buffs/debuffs (but for other testing I had deactivated this addon and still got the error, so it shouldn't be the cause)
Plater but for enemy nameplates only, so it shouldn't affect it
Raid fade even more to change the opacity of raid frames of players that are out of range
Raid frame anchor to change the positioning of the raid frames
Also some weakauras to add glows for certain debuffs, but the error occured in some fights where no weakaura was used

**Comment by creed-us** [comment]
It'd be reasonable to rule out anything that doesn't directly modify the compact unit frames - so it could be an interaction with Raid frame anchor or Raid fade, although that can't be for certain. I'll be making some time to look into it. Thank you for the help so far!

**Comment by matcoga** [comment]
I still have this error in 2.3.3 :

```
2x ...Ons/Overshields_Reforged/CompactUnitFrame_Update.lua:10: calling 'ClearAllPoints' on bad self (Usage: self:ClearAllPoints())
[Overshields_Reforged/CompactUnitFrame_Update.lua]:10: in function <...Ons/Overshields_Reforged/CompactUnitFrame_Update.lua:5>
[C]: in function 'CompactUnitFrameUtil_UpdateFillBar'
[Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua]:1159: in function <...Ons/Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua:1024>
[C]: in function 'CompactUnitFrame_UpdateHealPrediction'
[Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua]:429: in function 'CompactUnitFrame_UpdateAll'
[Blizzard_UnitFrame/Mainline/CompactUnitFrame.lua]:255: in function 'CompactUnitFrame_SetUnit'
[Blizzard_NamePlates/Blizzard_NamePlates.lua]:544: in function 'OnAdded'
[Blizzard_NamePlates/Blizzard_NamePlates.lua]:143: in function 'OnNamePlateAdded'
[Blizzard_NamePlates/Blizzard_NamePlates.lua]:79: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:70>

Locals:
frame = Button {
 WidgetContainer = Frame {
 }
 classificationIndicator = Texture {
 }
 HealthBarsContainer = Frame {
 }
 RaidTargetFrame = Frame {
 }
 maxDispelDebuffs = 0
 inVehicle = false
 optionTable = <table> {
 }
 overAbsorbGlow = Texture {
 }
 SoftTargetFrame = Frame {
 }
 totalAbsorb = Texture {
 }
 name = FontString {
 }
 aggroHighlight = Texture {
 }
 needsUpdate = true
 myHealAbsorbRightShadow = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 PlayerLevelDiffFrame = Frame {
 }
 ignoreCUFNameRequirement = true
 selectionHighlight = Texture {
 }
 myHealAbsorbLeftShadow = Texture {
 }
 maxDebuffs = 0
 unit = "nameplate1"
 unitExists = true
 disableMouse = true
 newUnit = true
 healPredictionDirty = true
 hideCastbar = true
 castBar = StatusBar {
 }
 displayedUnit = "nameplate1"
 hideHealthBarMask = 4
 BuffFrame = Frame {
 }
 LoseAggroAnim = AnimationGroup {
 }
 ClassificationFrame = Frame {
 }
 myHealAbsorb = Texture {
 }
 maxBuffs = 0
 totalAbsorbOverlay = Texture {
 }
 otherHealPrediction = Texture {
 }
 myHealPrediction = Texture {
 }
 isLootObject = false
 healthBar = StatusBar {
 }
}
previousTexture = Texture {
}
bar = Texture {
 overlay = Texture {
 }
}
amount = 0
barOffsetXPercent = nil
```


The new event Dastardly Duos allowed me to trigger the error systematically (join solo and wait for the npc helpers to spawn), and so I tested to enter without any addon except overshields and buggrabber, and I still have the error so it doesn't seem to be caused by any interaction with another addon.

**Comment by matcoga** [comment]
For your information, this error also occurs without being in a group by turning on friendly nameplate in any instance (for example The Rookery) (without any addon).

**Comment by matcoga** [comment]
I was curious and I did some playing around. I can confirm the error appeared with the version 2.3.0, with I think the addition of hooksecurefunc("CompactUnitFrameUtil_UpdateFillBar", ...) in CompactUnitFrame_Update.lua.
I'm wondering exactly what is the purpose of the call to ClearAllPoints here ? Removing it didn't seem to affect the behaviour of the addon (but I may be completely wrong about that).
Also, from my testing, this error only happens in instances, not in the open world (I did verify that the hook function is called both in instances and in the open world), so maybe blizzard handles frames differently in instances.

**Comment by creed-us** [comment]
I did some testing on my own and I am unfortunately at no better conclusion than I was 2 weeks ago. It was sometimes necessary to clear all points prior to the heal prediction being updated due to a possible bug I had encountered when loading into an instance or switching characters but could not reliably reproduce. I implemented some changes to prevent errors from popping up, and meanwhile I will try to do further testing to find a better solution. I tested using the steps you described earlier with v2.3.5 and it produced no errors, but I will continue to monitor. There should be a chat message if it happens but I've yet to encounter it in my testing.

**Comment by matcoga** [comment]
I looked at the changes you added in v2.3.5, and I tried to tweak them a bit to keep the ClearAllPoints hooked to CompactUnitFrameUtil_UpdateFillBar.

It turns out : 
if you modify the condition in the hook to CompactUnitFrameUtil_UpdateFillBar like the code you wrote in your local function clearAllPoints(), you still get the error
but if you add the use of pcall, you don't get the error (the flag IsForbidden() becomes true), even though it's technically the same code.

What I think is happening : 
the texture on which the code tries to call ClearAllPoints() is deleted or removed by blizzard before the object bar is updated to reflect that, which produces the error because the bar is invalid but we don't know it yet. However with the use of pcall, it musts slightly delay the call to the methods (clearallpoints, isfordidden, ...), and so the object bar has the time to be updated to be flagged forbidden and so the call to ClearAllPoints() is prevented.

This is the code I've tested (keeping the rest of CompactUnitFrame_Update.lua as it was in v2.3.3) :
```
-- Securely hook into the base UI function to clear points before it sets them
hooksecurefunc("CompactUnitFrameUtil_UpdateFillBar", function(frame, previousTexture, bar, amount, barOffsetXPercent)
    if bar == frame.totalAbsorb or bar == frame.totalAbsorbOverlay then
        local _, _ = pcall(function()
            if bar.ClearAllPoints and not (bar.IsForbidden and bar:IsForbidden()) then
                bar:ClearAllPoints()
            end
        end)
    end
end)
```

I've removed the prints in case of an error, because from my testing, if the call to ClearAllPoints() were to generate an error, bar:GetName() would have the same error.

This code seems to fix the badself error but I don't know if it would still fix the bug you were encountering before.

**Comment by creed-us** [comment]
I feel you may be right - this could be a race condition somehow but I haven't dug deep enough into the game's UI code to figure that out... I came up with a solution which appears to resolve the issue. There seems to be a way for me to validate the 'bar' but I had no success with it, nor was it inexpensive. There doesn't seem to be a simple way to check whether 'bar' is suitable for calling ClearAllPoints. This block is being called quite frequently, so with the goal of keeping performance impact minimal, I'm going to stick with using the method in v2.3.6 which implements pcall usage:
```
hooksecurefunc("CompactUnitFrameUtil_UpdateFillBar", function(frame, _, bar)
	if (bar == frame.totalAbsorb or bar == frame.totalAbsorbOverlay or bar == frame.overAbsorbGlow) then
		pcall(bar.ClearAllPoints, bar)
	end
end)
```

**Comment by matcoga** [comment]
This last solution does indeed technically solve the issue by just ignoring the error, but it may be the best solution performance-wise instead of trying to prevent the call. The question would be : is adding a condition with IsForbidden() inside the pcall more time consuming that just performing the call which will return an error ? (the theoretical best solution would be to not do the call at all, but then it brings back the bugs you were mentioning)
Anyway, as I said at the beginning, the error doesn't seem to create any bug (and it would be consistent with the hypothesis of trying to call ClearAllPoints on a no-longer valid object), so I think it's safe to consider the issue closed and accept to do more calls than strictly necessary.
Thank you for the time you took to investigate and try to find a fix to this resilient error.

**Comment by creed-us** [comment]
As ClearAllPoints() is not flagged as protected, we're able to call it whenever without issue. It perhaps saves 1-2 nanoseconds if anything, but as it should always evaluate to `true` in this instance, and this is in a hook which is called somewhere on the order of 1-10 times per second in some cases, I deemed it redundant and unnecessary.
